apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9kZXY6REVWQGZpdGZ1c2lvbmNsdXN0ZXIwLjN3d2FhLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1GaXRGdXNpb25DbHVzdGVyMA==
  JWT_SECRET: dHVfc2VjcmV0b19qd3Q=
  GOOGLE_CLIENT_ID: NjM0MzU1MDI5OTUtM2Q1dXRxcmI2bmsqamU3aGtyN2Fwbg==
  GOOGLE_CLIENT_SECRET: R09DU1BYLUpTRE5pMFlEbWZ4XzNQdW1WTU9rNVI2d2hhX0M=
